"""Semantic narrative check (β-JP-1 chain 1b T2).

byte-diff is only valid for deterministic generators (template / mock). Real
LLM output on the remote server is non-reproducible, so this module is the
verification gate there: ``check_narratives(cif_dir, version_id,
expectations)`` walks one narrative version and returns a fail-loud
``SemanticCheckReport`` covering 5 axes:

1. **structure** — every structural document stub has a narrative file (and
   no orphan narrative files exist); composition section keys match the
   ``DocumentTypeSpec.composition_sections`` registry exactly; no empty
   section / empty free-text body; ``generator_metadata`` fallback ratio
   (an LLM version with ``template_fallback`` docs = partial provider
   failure = finding).
2. **facts** — ``facts_used`` tags must come from the structural-CIF-derived
   vocabulary (``_ALLOWED_FACT_PREFIXES``); docs whose spec routes sections
   to the LLM must carry a non-empty ``facts_used`` (traceability).
3. **forbidden_pattern** — builtin hallucination / meta-response detection
   (``As an AI`` / ``I cannot`` / ``[Mock`` / unresolved ``{placeholder}`` /
   TEMPLATE SEED instruction leakage) + locale violation (Japanese chars in
   a non-ja version, excluding
   ``clinosim.modules.document.audit.KNOWN_JA_ONLY_FALLBACK_SECTIONS``).
4. **phrase** — per-profile expectations YAML: required (``all_of`` /
   ``any_of``) and ``forbidden`` phrases per (document_type, section).
5. **numeric** — optional per-section numeric facts (``numeric`` entries in
   the expectations YAML) must appear in the text within tolerance.

Mock-version exemptions: a version whose manifest ``generator`` is
``llm-mock`` was *intentionally* generated by the deterministic MockProvider
(local pipeline verification). For that generator only, the ``[Mock``
builtin pattern and the phrase/numeric expectations on
``spec.llm_enabled_sections`` are skipped (those sections carry mock stub
text, not clinical narrative); skip counts are recorded in ``report.info``.
On any real provider version (``llm-ollama`` / ``llm-bedrock``), ``[Mock``
markers fail — they indicate a silently mis-wired provider.

Expectations YAML schema (``<profile>.llm-expectations.yaml``)::

    global:
      forbidden_patterns: ["<regex>", ...]      # extra, builtin set always applies
    <document_type>:                            # e.g. admission_hp
      <section>:                                # composition section key, or "text"
        all_of: ["<substring>", ...]            # every phrase required
        any_of: ["<substring>", ...]            # at least one required
        forbidden: ["<substring>", ...]         # none may appear
        numeric:                                # optional numeric facts
          - {value: 11, tolerance: 1}

``load_expectations`` validates fail-loud: unknown document types (vs the
DocumentTypeSpec registry), unknown section keys (vs the spec's
``composition_sections`` + the special ``"text"`` key), unknown entry keys,
malformed regexes and numeric entries all raise ``ValueError``.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

import yaml

from clinosim.modules.document.audit import _JA_CHAR_RE, KNOWN_JA_ONLY_FALLBACK_SECTIONS
from clinosim.modules.document.narrative.registry import load_document_type_specs
from clinosim.types.document import (
    DocumentTypeSpec,
    FormatType,
    SemanticCheckFinding,
    SemanticCheckReport,
)

__all__ = ["check_narratives", "load_expectations"]

#: Manifest generator value written by `narrate --provider mock` — the only
#: generator for which mock-marker text is expected (see module docstring).
MOCK_GENERATOR = "llm-mock"

#: Special expectations section key: the whole document body (free_text
#: `narrative.text`, or all composition sections joined for composition docs).
TEXT_SECTION_KEY = "text"

#: facts_used tag vocabulary — every tag written by
#: `TemplateNarrativeGenerator` (and preserved verbatim by the LLM
#: replacement strategy) starts with one of these structural-CIF-derived
#: prefixes. Anything else = corrupted / fabricated provenance.
_ALLOWED_FACT_PREFIXES: tuple[str, ...] = (
    "ctx.",
    "disease_protocol.",
    "encounter_protocol.",
    "physical_exam_findings",
    "discharge_instructions",
    "patient.",
    "profile.",
    "chronic.",
    "encounter.",
)

#: Builtin forbidden patterns (axis 3): meta/AI responses, mock markers,
#: unresolved template placeholders, narrative_seed prompt leakage.
_BUILTIN_FORBIDDEN_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = tuple(
    (label, re.compile(pattern))
    for label, pattern in (
        ("AI meta-response", r"As an AI"),
        ("refusal meta-response", r"I cannot"),
        ("mock provider marker", r"\[Mock"),
        ("unresolved placeholder", r"\{[a-zA-Z_][a-zA-Z0-9_]*\}"),
        ("seed prompt leakage", r"TEMPLATE SEED|END SEED"),
        ("seed instruction leakage (en)", r"Generate an improved version"),
        ("seed instruction leakage (ja)", r"改善後のセクション本文"),
    )
)

_MOCK_EXEMPT_PATTERN_LABELS = frozenset({"mock provider marker"})

_EXPECTATION_ENTRY_KEYS = frozenset({"all_of", "any_of", "forbidden", "numeric"})

_NUMBER_RE = re.compile(r"-?\d+(?:\.\d+)?")


def load_expectations(path: str | Path) -> dict[str, Any]:
    """Load + fail-loud validate a `<profile>.llm-expectations.yaml` file.

    Returns the parsed dict (shape per module docstring). Raises
    ``ValueError`` on any schema violation and ``FileNotFoundError`` on a
    missing file — a typo'd doc type or section key must never silently
    no-op the check (PR-90 class).
    """
    p = Path(path)
    data = yaml.safe_load(p.read_text(encoding="utf-8"))
    if data is None:
        data = {}
    if not isinstance(data, dict):
        raise ValueError(f"{p.name}: top level must be a mapping, got {type(data).__name__}")

    specs = load_document_type_specs()
    specs_by_key: dict[str, DocumentTypeSpec] = {dt.value: spec for dt, spec in specs.items()}

    for doc_key, sections in data.items():
        if doc_key == "global":
            _validate_global(p.name, sections)
            continue
        spec = specs_by_key.get(str(doc_key))
        if spec is None:
            raise ValueError(
                f"{p.name}: unknown document type {doc_key!r} — allowed: {sorted(specs_by_key)} (+ 'global')"
            )
        if not isinstance(sections, dict) or not sections:
            raise ValueError(f"{p.name}[{doc_key}]: must be a non-empty section mapping")
        # P2-13 PR2a (session 47): allow both US and JP-CLINS section keys
        # so a single expectations file can carry per-country checks. The
        # spec accessor returns the JP list when composition_sections_jp is
        # populated; we union both to accept any valid section key.
        allowed_sections = (
            set(spec.composition_sections) | set(spec.composition_sections_for("JP")) | {TEXT_SECTION_KEY}
        )
        for section_key, entry in sections.items():
            if section_key not in allowed_sections:
                raise ValueError(
                    f"{p.name}[{doc_key}]: unknown section {section_key!r} — allowed: {sorted(allowed_sections)}"
                )
            _validate_entry(p.name, doc_key, section_key, entry)
    return data


def _validate_global(filename: str, entry: Any) -> None:
    if not isinstance(entry, dict):
        raise ValueError(f"{filename}[global]: must be a mapping")
    unknown = set(entry) - {"forbidden_patterns"}
    if unknown:
        raise ValueError(f"{filename}[global]: unknown keys {sorted(unknown)} — allowed: ['forbidden_patterns']")
    patterns = entry.get("forbidden_patterns", [])
    if not isinstance(patterns, list):
        raise ValueError(f"{filename}[global.forbidden_patterns]: must be a list")
    for pattern in patterns:
        try:
            re.compile(str(pattern))
        except re.error as exc:
            raise ValueError(f"{filename}[global.forbidden_patterns]: invalid regex {pattern!r} ({exc})") from exc


def _validate_entry(filename: str, doc_key: str, section_key: str, entry: Any) -> None:
    where = f"{filename}[{doc_key}.{section_key}]"
    if not isinstance(entry, dict) or not entry:
        raise ValueError(f"{where}: must be a non-empty mapping")
    unknown = set(entry) - _EXPECTATION_ENTRY_KEYS
    if unknown:
        raise ValueError(f"{where}: unknown keys {sorted(unknown)} — allowed: {sorted(_EXPECTATION_ENTRY_KEYS)}")
    for list_key in ("all_of", "any_of", "forbidden"):
        value = entry.get(list_key, [])
        if not isinstance(value, list) or any(not str(v).strip() for v in value):
            raise ValueError(f"{where}.{list_key}: must be a list of non-empty phrases")
    numeric = entry.get("numeric", [])
    if not isinstance(numeric, list):
        raise ValueError(f"{where}.numeric: must be a list of {{value, tolerance}} entries")
    for item in numeric:
        if not isinstance(item, dict) or "value" not in item:
            raise ValueError(f"{where}.numeric: each entry needs a 'value' key")
        unknown_nk = set(item) - {"value", "tolerance"}
        if unknown_nk:
            raise ValueError(f"{where}.numeric: unknown keys {sorted(unknown_nk)}")
        if not isinstance(item["value"], (int, float)) or isinstance(item["value"], bool):
            raise ValueError(f"{where}.numeric: 'value' must be a number")
        tolerance = item.get("tolerance", 0)
        if not isinstance(tolerance, (int, float)) or isinstance(tolerance, bool) or tolerance < 0:
            raise ValueError(f"{where}.numeric: 'tolerance' must be a number >= 0")


def check_narratives(
    cif_dir: str,
    version_id: str,
    expectations: dict[str, Any] | None = None,
) -> SemanticCheckReport:
    """Run the 5-axis semantic check over ``cif_dir/narratives/<version_id>``.

    ``expectations`` is a dict already validated by ``load_expectations``
    (or None → builtin axes 1-3 only). Never raises on narrative content —
    every violation becomes a finding; only broken inputs (missing
    structural CIF tree) produce an immediate structure finding.
    """
    report = SemanticCheckReport(cif_dir=cif_dir, version_id=version_id)
    expectations = expectations or {}

    structural_dir = os.path.join(cif_dir, "structural", "patients")
    version_dir = os.path.join(cif_dir, "narratives", version_id)
    narrative_dir = os.path.join(version_dir, "documents")

    if not os.path.isdir(structural_dir):
        report.findings.append(
            SemanticCheckFinding(
                axis="structure",
                message=f"structural CIF tree missing: {structural_dir}",
            )
        )
        return report
    if not os.path.isdir(narrative_dir):
        report.findings.append(
            SemanticCheckFinding(
                axis="structure",
                message=f"narrative version tree missing: {narrative_dir}",
            )
        )
        return report

    manifest = _load_manifest(version_dir, report)
    generator = str(manifest.get("generator", ""))
    is_mock = generator == MOCK_GENERATOR
    languages_used = list(manifest.get("languages_used") or [])
    check_ja_leak = "ja" not in languages_used

    specs_by_key: dict[str, DocumentTypeSpec] = {dt.value: spec for dt, spec in load_document_type_specs().items()}
    extra_patterns = [re.compile(str(pat)) for pat in (expectations.get("global") or {}).get("forbidden_patterns", [])]

    generator_counts: dict[str, int] = {}
    skipped_mock_sections = 0
    empty_facts_template_only = 0
    seen_files: set[str] = set()

    patient_files = sorted(f for f in os.listdir(structural_dir) if f.endswith(".json"))
    for pf in patient_files:
        with open(os.path.join(structural_dir, pf), encoding="utf-8") as f:
            patient = json.load(f)
        encounters = patient.get("encounters") or []
        encounter_id = str(encounters[0].get("encounter_id", "")) if encounters else ""
        for stub in patient.get("documents") or []:
            document_id = str(stub.get("document_id", ""))
            task_type = str(stub.get("task_type", ""))
            report.document_count += 1
            narrative_path = os.path.join(narrative_dir, encounter_id, f"{document_id}.json")
            if not os.path.exists(narrative_path):
                report.findings.append(
                    SemanticCheckFinding(
                        axis="structure",
                        document_id=document_id,
                        message=f"narrative file missing for stub (task_type={task_type})",
                    )
                )
                continue
            seen_files.add(os.path.relpath(narrative_path, narrative_dir))
            with open(narrative_path, encoding="utf-8") as f:
                narrative = (json.load(f).get("narrative")) or {}

            spec = specs_by_key.get(task_type)
            if spec is None:
                report.findings.append(
                    SemanticCheckFinding(
                        axis="structure",
                        document_id=document_id,
                        message=f"unknown task_type {task_type!r} (not in DocumentTypeSpec registry)",
                    )
                )
                continue

            gen_meta = str((narrative.get("generator_metadata") or {}).get("generator", ""))
            generator_counts[gen_meta] = generator_counts.get(gen_meta, 0) + 1

            sections = _sections_of(narrative, spec)
            _check_structure(report, document_id, spec, narrative)
            empty_facts_template_only += _check_facts(report, document_id, spec, narrative)
            _check_forbidden(
                report,
                document_id,
                sections,
                is_mock=is_mock,
                check_ja_leak=check_ja_leak,
                extra_patterns=extra_patterns,
            )
            skipped_mock_sections += _check_expectations(
                report,
                document_id,
                spec,
                sections,
                expectations.get(task_type) or {},
                is_mock=is_mock,
            )

    _check_orphans(report, narrative_dir, seen_files)

    if generator.startswith("llm-"):
        fallback = generator_counts.get("template_fallback", 0)
        if fallback:
            report.findings.append(
                SemanticCheckFinding(
                    axis="structure",
                    message=(
                        f"{fallback} document(s) fell back to template output on an "
                        f"LLM version ({generator}) — partial provider failure; "
                        f"generator counts: {generator_counts}"
                    ),
                )
            )

    report.info["generator"] = generator
    report.info["generator_counts"] = generator_counts
    report.info["languages_used"] = languages_used
    report.info["skipped_mock_llm_sections"] = skipped_mock_sections
    report.info["empty_facts_template_only_docs"] = empty_facts_template_only
    return report


def _load_manifest(version_dir: str, report: SemanticCheckReport) -> dict[str, Any]:
    manifest_path = os.path.join(version_dir, "manifest.json")
    if not os.path.exists(manifest_path):
        report.findings.append(
            SemanticCheckFinding(
                axis="structure",
                message=f"manifest.json missing: {manifest_path}",
            )
        )
        return {}
    with open(manifest_path, encoding="utf-8") as f:
        loaded = json.load(f)
    return loaded if isinstance(loaded, dict) else {}


def _sections_of(narrative: dict[str, Any], spec: DocumentTypeSpec) -> dict[str, str]:
    """Checkable (section → text) map incl. the synthetic ``"text"`` key."""
    sections = dict(narrative.get("sections") or {})
    if spec.format_type == FormatType.COMPOSITION:
        sections[TEXT_SECTION_KEY] = "\n\n".join(str(v) for v in (narrative.get("sections") or {}).values())
    else:
        sections[TEXT_SECTION_KEY] = str(narrative.get("text", "") or "")
    return sections


def _check_structure(
    report: SemanticCheckReport,
    document_id: str,
    spec: DocumentTypeSpec,
    narrative: dict[str, Any],
) -> None:
    """Axis 1 (per-document part): section key set + non-empty content."""
    sections = narrative.get("sections") or {}
    if spec.format_type == FormatType.COMPOSITION:
        # P2-13 PR2a (session 47): a doc may follow either the US
        # composition_sections list or, when country=JP, the JP-CLINS
        # composition_sections_jp list. Both are registry-valid — flag drift
        # only when the actual set matches NEITHER country variant.
        us_expected = set(spec.composition_sections)
        jp_expected = set(spec.composition_sections_for("JP"))
        actual = set(sections)
        if actual != us_expected and actual != jp_expected:
            # Report drift against the closest variant so the message is useful.
            us_delta = (
                (us_expected - actual),
                (actual - us_expected),
                "us",
            )
            jp_delta = (
                (jp_expected - actual),
                (actual - jp_expected),
                "jp",
            )
            closest = (
                us_delta if (len(us_delta[0]) + len(us_delta[1]) <= len(jp_delta[0]) + len(jp_delta[1])) else jp_delta
            )
            missing, extra, variant = closest
            report.findings.append(
                SemanticCheckFinding(
                    axis="structure",
                    document_id=document_id,
                    message=(
                        f"composition section keys drift from registry "
                        f"(closest={variant}): "
                        f"missing={sorted(missing)}, extra={sorted(extra)}"
                    ),
                )
            )
        for key, text in sections.items():
            if not str(text).strip():
                report.findings.append(
                    SemanticCheckFinding(
                        axis="structure",
                        document_id=document_id,
                        section=key,
                        message="empty section text",
                    )
                )
    else:
        if not str(narrative.get("text", "") or "").strip():
            report.findings.append(
                SemanticCheckFinding(
                    axis="structure",
                    document_id=document_id,
                    message="empty free-text narrative body",
                )
            )


def _check_facts(
    report: SemanticCheckReport,
    document_id: str,
    spec: DocumentTypeSpec,
    narrative: dict[str, Any],
) -> int:
    """Axis 2: facts_used provenance. Returns 1 if empty-but-tolerated (info)."""
    facts = list(narrative.get("facts_used") or [])
    for tag in facts:
        if not str(tag).startswith(_ALLOWED_FACT_PREFIXES):
            report.findings.append(
                SemanticCheckFinding(
                    axis="facts",
                    document_id=document_id,
                    message=(
                        f"facts_used tag {tag!r} outside the structural-CIF "
                        f"vocabulary (allowed prefixes: {list(_ALLOWED_FACT_PREFIXES)})"
                    ),
                )
            )
    if not facts:
        # Deviation from spec §1-T2 ("facts_used non-empty" unconditionally):
        # template_only docs legitimately emit facts_used=[] today (e.g.
        # admission_nursing_assessment built purely from fallback phrases), so
        # empty facts is a FINDING only where LLM sections exist (traceability
        # of LLM-touched docs) and an info counter otherwise.
        if spec.llm_enabled_sections:
            report.findings.append(
                SemanticCheckFinding(
                    axis="facts",
                    document_id=document_id,
                    message="facts_used is empty on an LLM-enabled document type",
                )
            )
        else:
            return 1
    return 0


def _check_forbidden(
    report: SemanticCheckReport,
    document_id: str,
    sections: dict[str, str],
    *,
    is_mock: bool,
    check_ja_leak: bool,
    extra_patterns: list[re.Pattern[str]],
) -> None:
    """Axis 3: builtin + expectations-global forbidden patterns, JA leak."""
    for section_key, text in sections.items():
        text = str(text)
        if section_key == TEXT_SECTION_KEY and len(sections) > 1:
            # Composition: the synthetic joined text duplicates the per-section
            # bodies — skip to avoid double findings. (Free-text docs have
            # sections == {"text": ...} only, so their body IS checked.)
            continue
        for label, pattern in _BUILTIN_FORBIDDEN_PATTERNS:
            if is_mock and label in _MOCK_EXEMPT_PATTERN_LABELS:
                continue
            match = pattern.search(text)
            if match:
                report.findings.append(
                    SemanticCheckFinding(
                        axis="forbidden_pattern",
                        document_id=document_id,
                        section=section_key,
                        message=f"{label}: matched {match.group(0)!r}",
                    )
                )
        for pattern in extra_patterns:
            match = pattern.search(text)
            if match:
                report.findings.append(
                    SemanticCheckFinding(
                        axis="forbidden_pattern",
                        document_id=document_id,
                        section=section_key,
                        message=f"global forbidden pattern {pattern.pattern!r} matched {match.group(0)!r}",
                    )
                )
        # JA-leak axis is composition-section-scoped, mirroring the Bug A
        # audit gate (`_count_us_hp_ja_chars`): free-text bodies (progress /
        # nursing shift notes) still carry Japanese from the SAME tracked
        # disease-YAML no-per-language-split data gap that
        # KNOWN_JA_ONLY_FALLBACK_SECTIONS covers for composition sections
        # (see `clinosim/modules/document/audit.py` module docstring TODO).
        # Checking whole free-text bodies would perpetually fail on that
        # known, separately-tracked issue instead of catching regressions.
        if (
            check_ja_leak
            and section_key != TEXT_SECTION_KEY
            and section_key not in KNOWN_JA_ONLY_FALLBACK_SECTIONS
            and _JA_CHAR_RE.search(text)
        ):
            report.findings.append(
                SemanticCheckFinding(
                    axis="forbidden_pattern",
                    document_id=document_id,
                    section=section_key,
                    message="Japanese characters in a non-ja narrative version",
                )
            )


def _check_expectations(
    report: SemanticCheckReport,
    document_id: str,
    spec: DocumentTypeSpec,
    sections: dict[str, str],
    doc_expectations: dict[str, Any],
    *,
    is_mock: bool,
) -> int:
    """Axes 4+5: required/forbidden phrases + numeric facts. Returns mock skips."""
    skipped = 0
    # P2-13 PR2a (session 47): union of US + JP LLM-enabled sections so the
    # mock exemption fires regardless of which locale variant produced the
    # section keys under check.
    llm_enabled = set(spec.llm_enabled_sections) | set(spec.llm_enabled_sections_jp)
    for section_key, entry in doc_expectations.items():
        if is_mock and section_key in llm_enabled:
            # Mock stub text is not clinical narrative — expectations on
            # LLM-replaced sections only make sense for real providers.
            skipped += 1
            continue
        text = str(sections.get(section_key, ""))
        for phrase in entry.get("all_of", []):
            if str(phrase) not in text:
                report.findings.append(
                    SemanticCheckFinding(
                        axis="phrase",
                        document_id=document_id,
                        section=section_key,
                        message=f"required phrase missing: {phrase!r}",
                    )
                )
        any_of = [str(p) for p in entry.get("any_of", [])]
        if any_of and not any(p in text for p in any_of):
            report.findings.append(
                SemanticCheckFinding(
                    axis="phrase",
                    document_id=document_id,
                    section=section_key,
                    message=f"none of the expected phrases found: {any_of}",
                )
            )
        for phrase in entry.get("forbidden", []):
            if str(phrase) in text:
                report.findings.append(
                    SemanticCheckFinding(
                        axis="phrase",
                        document_id=document_id,
                        section=section_key,
                        message=f"forbidden phrase present: {phrase!r}",
                    )
                )
        numeric = entry.get("numeric", [])
        if numeric:
            numbers = [float(m) for m in _NUMBER_RE.findall(text)]
            for item in numeric:
                value = float(item["value"])
                tolerance = float(item.get("tolerance", 0))
                if not any(abs(n - value) <= tolerance for n in numbers):
                    report.findings.append(
                        SemanticCheckFinding(
                            axis="numeric",
                            document_id=document_id,
                            section=section_key,
                            message=(f"numeric fact {value} (±{tolerance}) not found in section text"),
                        )
                    )
    return skipped


def _check_orphans(report: SemanticCheckReport, narrative_dir: str, seen_files: set[str]) -> None:
    """Axis 1 (tree part): narrative files without a matching structural stub."""
    for root, _dirs, files in os.walk(narrative_dir):
        for name in files:
            if not name.endswith(".json"):
                continue
            rel = os.path.relpath(os.path.join(root, name), narrative_dir)
            if rel not in seen_files:
                report.findings.append(
                    SemanticCheckFinding(
                        axis="structure",
                        message=f"orphan narrative file without structural stub: {rel}",
                    )
                )
