"""Antibiotic regimens generated by modules/antibiotic for HAI events (PR3b-1)."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class AntibioticRegimen:
    """One empirical antibiotic regimen attached to a single HAI event.

    Stored as list[AntibioticRegimen] under
    CIFPatientRecord.extensions["antibiotic"]. The hai_event_id field
    links each regimen back to the HAIEvent (extensions["hai"]) that
    triggered it — this is the cross-module consumption point for
    PR3b-2 (S/I/R), PR3b-3 (narrow), and PR3b-4 (WBC/CRP decay).

    discontinuation_datetime is None for PR3b-1 empirical regimens that
    ran their full duration. PR3b-3 narrow will set it when the broad
    regimen is truncated.
    """

    regimen_id: str = ""
    hai_event_id: str = ""
    encounter_id: str = ""
    drug_key: str = ""  # canonical name in modules.antibiotic.ANTIBIOTIC_DRUGS
    dose: str = ""  # e.g. "1g", "3.375g"
    route: str = ""  # "IV" for PR3b-1
    frequency: str = ""  # "q12h" / "q6h" / "q24h"
    start_datetime: datetime = field(default_factory=lambda: datetime(1970, 1, 1))
    duration_days: int = 0
    intent: str = "empirical"  # "empirical" | "narrowed" (PR3b-3 reserves)
    discontinuation_datetime: datetime | None = None
