"""Prophylaxis engine — YAML loader + skip-condition dispatch + order builder.

Determinism: no RNG consumption. Every decision is a pure function of
patient / encounter state + the yaml rule set.
"""

from __future__ import annotations

from datetime import datetime, timedelta
from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

_HERE = Path(__file__).resolve().parent
_YAML_PATH = _HERE / "reference_data" / "prophylaxis_rules.yaml"


@lru_cache(maxsize=1)
def _load_rules() -> dict[str, Any]:
    with _YAML_PATH.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _dvt_rule() -> dict[str, Any]:
    return _load_rules().get("dvt_prophylaxis", {}) or {}


def _skip_conditions() -> dict[str, dict[str, Any]]:
    return _load_rules().get("skip_conditions", {}) or {}


def should_skip_dvt_prophylaxis(
    *,
    patient: Any,
    encounter: Any,
    admission_dx_code: str = "",
    active_medications: list[str] | None = None,
) -> tuple[bool, str]:
    """Return ``(skip, reason)`` — the enricher records ``reason`` in the
    trace so audit consumers can see WHY prophylaxis was withheld.

    Args:
        patient: PatientProfile-like (reads ``current_medications`` if
            ``active_medications`` is None).
        encounter: Encounter with ``admission_datetime`` / ``discharge_datetime``.
        admission_dx_code: ICD code from ``clinical_diagnosis``. Empty string
            means no dx available — do not skip on the dx-based rules.
        active_medications: optional pre-computed list of drug-name strings.

    Never raises. If the rule yaml is malformed, returns ``(False, "")`` so
    the caller emits prophylaxis (safe default).
    """
    conditions = _skip_conditions()

    # Rule 1: therapeutic anticoagulant on board.
    if active_medications is None:
        active_medications = [
            getattr(m, "drug_name", None) or getattr(m, "drug", None) or ""
            for m in (getattr(patient, "current_medications", None) or [])
        ]
    active_lower = [str(m).lower() for m in active_medications if m]

    ac_rule = conditions.get("therapeutic_anticoagulant_active", {}) or {}
    for needle in ac_rule.get("drug_needles", []) or []:
        n = str(needle).lower()
        if any(n in m for m in active_lower):
            return True, "therapeutic_anticoagulant_active"

    # Rule 2/3/4: ICD-prefix conditions on admission dx.
    if admission_dx_code:
        dx_upper = admission_dx_code.upper().strip()
        for rule_name in (
            "active_bleeding_or_hemorrhage",
            "perinatal_delivery",
            "active_dvt_pe_treatment",
        ):
            rule = conditions.get(rule_name, {}) or {}
            for prefix in rule.get("icd_prefixes", []) or []:
                if dx_upper.startswith(str(prefix).upper()):
                    return True, rule_name

    return False, ""


def _encounter_los_hours(encounter: Any) -> float:
    adm = getattr(encounter, "admission_datetime", None) or (
        encounter.get("admission_datetime") if isinstance(encounter, dict) else None
    )
    dc = getattr(encounter, "discharge_datetime", None) or (
        encounter.get("discharge_datetime") if isinstance(encounter, dict) else None
    )
    if adm is None or dc is None:
        return 0.0
    try:
        if isinstance(adm, str):
            adm = datetime.fromisoformat(adm)
        if isinstance(dc, str):
            dc = datetime.fromisoformat(dc)
        return max(0.0, (dc - adm).total_seconds() / 3600.0)
    except (TypeError, ValueError):
        return 0.0


def _admission_dx_from_record(record: Any) -> str:
    """Extract admission / discharge ICD code from record.clinical_diagnosis."""
    cd = getattr(record, "clinical_diagnosis", None)
    if cd is None:
        return ""
    for attr in ("discharge_diagnosis_code", "admission_diagnosis_code"):
        v = getattr(cd, attr, "") or ""
        if v:
            return str(v)
    return ""


def build_dvt_prophylaxis_orders(
    *,
    record: Any,
    encounter_id_override: str = "",
) -> list[Any]:
    """Return a list of ``Order`` dataclasses (each ready to be appended
    to ``record.orders``) representing the DVT prophylaxis regimen for
    the encounter's LOS.

    Emits one Order (Enoxaparin 40 mg SC daily). The matching
    MedicationAdministration rows can be added by the caller if the
    sim detail level warrants them; the Order alone is the load-bearing
    FHIR MedicationRequest signal.

    Never raises. Returns ``[]`` when the encounter should be skipped
    (short LOS, contraindication, therapeutic AC already on board).
    """
    encounters = getattr(record, "encounters", []) or []
    if not encounters:
        return []
    # Focus on the primary IMP encounter (records generated by
    # simulator.inpatient hold one encounter per record).
    enc = encounters[0]
    encounter_type = str(getattr(enc, "encounter_type", "") or "").lower()
    if encounter_type not in ("inpatient", "imp"):
        return []

    rule = _dvt_rule()
    min_los = float(rule.get("min_los_hours", 48))
    if _encounter_los_hours(enc) < min_los:
        return []

    patient = getattr(record, "patient", None)
    admission_dx = _admission_dx_from_record(record)
    skip, reason = should_skip_dvt_prophylaxis(
        patient=patient,
        encounter=enc,
        admission_dx_code=admission_dx,
    )
    if skip:
        return []

    encounter_id = encounter_id_override or (getattr(enc, "encounter_id", "") or "")
    if not encounter_id:
        return []

    adm_dt = getattr(enc, "admission_datetime", None)
    ordered_dt = adm_dt
    if isinstance(adm_dt, str):
        try:
            ordered_dt = datetime.fromisoformat(adm_dt) + timedelta(hours=6)
        except (TypeError, ValueError):
            ordered_dt = adm_dt
    elif isinstance(adm_dt, datetime):
        ordered_dt = adm_dt + timedelta(hours=6)

    # Emit as a real Order dataclass so downstream CLI debug printers and
    # any consumer expecting attribute access work uniformly.
    from clinosim.types.encounter import Order, OrderStatus, OrderType

    order = Order(
        order_id=f"ORD-{encounter_id}-DVT-01",
        encounter_id=encounter_id,
        patient_id=getattr(patient, "patient_id", "") if patient else "",
        order_type=OrderType.MEDICATION,
        order_code="",
        display_name=rule["drug"],
        urgency="routine",
        clinical_intent=rule.get("clinical_intent", ""),
        clinical_intent_ja=rule.get("clinical_intent_ja", ""),
        ordered_datetime=ordered_dt,
        ordered_by=getattr(enc, "attending_physician_id", "") or "",
        status=OrderStatus.PLACED,
        dose_quantity=rule.get("dose_quantity"),
        dose_unit=rule.get("dose_unit", ""),
        frequency=rule.get("frequency", ""),
        route=rule.get("route", "SC"),
    )
    return [order]
